title = "Algebra of nets"
base_url = "https://cause-effect.link"
compile_sass = true
highlight_code = false
build_search_index = true
theme = "juice-modified"

[extra]

author = "k7f"
logo_name = "stru<sup>C</sup>tur<sub>E</sub>s"
logo_path = "logo.jpg"
extra_menu = [
    { title = "Repository", link = "https://github.com/k7f/ascesis" }
]
repository_url = "https://github.com/k7f/ascesis"
